name: Update Dependencies
on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust tools
        run: |
          rustup update --no-self-update
          cargo install cargo-edit
      - name: Upgrade dependencies
        run: make upgrade

      # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "Update dependencies"
          title: "Update dependencies"
          branch: "update-dependencies"
          delete-branch: true
          reviewers: takkyuuplayer
